### ISSUE TITLE
The license needs to be the Apache / BSD license - not the MIT license

### ISSUE THREAD

**Issue by jonjoliver** [glaslos/tlsh#20]
Hi

this is great - I added a link to it.

But you have made the license MIT - which is not actually allowed under the license of TLSH.
Could you make the LICENSE.txt file the same as
https://github.com/trendmicro/tlsh/blob/master/LICENSE

Cheers
jono

**Comment by kung-foo** [comment]
IANAL, so treat this question accordingly, but what is the difference between implementing the TLSH 
_algorithm_ in another language (meaning zero code reuse) versus forking/changing the reference implementation?

**Comment by glaslos** [comment]
I think it boils down to if this is considered derivative work? Isn't the Apache license permissive in a way that if its not the same code but derivative work we don't have to release under the same license?

**Comment by glaslos** [comment]
@jonjoliver point here is not to piss you off, just to get some clarification. If you insist on Apache License 2.0, I think there is little reason for us to stick with MIT.

**Comment by jonjoliver** [comment]
Hi - do you need the MIT license?
If you need it I will ask my legal guy - and we will see if the MIT license is OK
OSSEC asked us this before - and thats when we moved to
     Apache OR BSD
because OSSEC needed BSD - and could not work easily with Apache

Is that what you need?
Because I think that is a better solution.

Cheers
jono

**Comment by jonjoliver** [comment]
kung-foo
changing licenses is tricky
This mainly comes up in the situations involving the GPL license
where people need to avoid the license
And I understand that just changing languages does get you away from the GPL license

But this situation is different
- we are happy to use to consider any respectable license - as long as it has the acknowledgement of the NOTICE.txt requirement (that was the basis of my company open sourcing the code)
- so let me check MIT license with my legal guy

**Comment by kung-foo** [comment]
Hi @jonjoliver, I'm more just trying to understand licenses in general here. I don't have a vested interest one way or the other. So no need to drag lawyers into this :)

**Comment by kung-foo** [comment]
I am curious about the dual license. Does that imply that all derivative works must also be dual licensed?

**Comment by jonjoliver** [comment]
> Does that imply that all derivative works must also be dual licensed?

I am not a lawyer so I do not know.
My personal understanding is that an OR license - means that you can pick either
There might be other types of dual license.
And I know some licenses are incompatible.
I was told by legal that Apache and BSD are compatible to do this

To get away from an existing license requires that you go through a "Clean room" process.
https://en.wikipedia.org/wiki/Clean_room_design

**Comment by glaslos** [comment]
Apache 2.0 and MIT are compatible. Can we just add Apache to what we have right now?

**Comment by jonjoliver** [comment]
sounds good

Thanks
jono

**Comment by glaslos** [comment]
Fixed in c7c0685f0bb9402b98000977feac032b61904da9
@jonjoliver please have a look at the NOTICE file as I made some changes.
