### ISSUE TITLE
Refactor the API to make it play nicer with other hashes

### ISSUE THREAD

**Issue by scudette** [glaslos/tlsh#24]
The current API looks like it takes a reader and reads the entire file by itself. This is not efficient when compared to other hashes in Go which offer a Writer interface. The advantage with a Writer interface is that the caller can supply repeated buffers to multiple hashes at the same time thereby allowing for a single read of the file, and fanning out to multiple hashes. This is most efficient for slow readers (e.g. zip file members etc) which repeated reading of the same file is too expensive.

Please consider to refactor the API to make it more similar to existing hashes to comply with the standard Hash interface:

https://pkg.go.dev/hash#Hash

I am not that familiar with this hash or if this is even possible for this specific algorithm so please feel free to dismiss this FR :-)

**Comment by glaslos** [comment]
Hi @scudette have a look at #25 and let me know if that works for you.

**Comment by glaslos** [comment]
Merged into main.
